trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'ALT-Test'
  loadTestResource: 'Demo-Podcast-EUS'
  loadTestResourceGroup: 'demo-podcast'
  webAppName: 'demo-podcastwebapp'

stages:
- stage: LoadTest
  displayName: Load Test
  jobs:
  - job: LoadTest
    displayName: Load Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureLoadTest@1
      inputs:
        azureSubscription: $(serviceConnection)
        loadTestConfigFile: 'Test/config.yml'
        resourceGroup: $(loadTestResourceGroup)
        loadTestResource: $(loadTestResource)
        env: |
            [
              {
              "name": "webapp",
              "value": "$(webAppName).azurewebsites.net"
              }
            ]
    - publish: $(System.DefaultWorkingDirectory)/loadTest
      artifact: results