trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'ALT-Test'
  loadTestResource: 'Demo-Podcast-EUS'
  loadTestResourceGroup: 'demo-podcast'
  location: 'EAST US'

stages:
- stage: LoadTest
  displayName: Load Test
  jobs:
  - job: LoadTest
    displayName: Load Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureLoadTest@1
      inputs:
        azureSubscription: $(serviceConnection)
        loadTestConfigFile: 'Test/config.yml'
        resourceGroup: $(loadTestResourceGroup)
        loadTestResource: $(loadTestResource)
          
    - publish: $(System.DefaultWorkingDirectory)/loadTest
      artifact: results